# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: r

apt_packages:
    - libgsl0-dev
    - libgsl0ldbl
    
r_binary_packages:
    - Rcpp
    - RcppGSL
 
r_github_packages: rmetaverse/pubBias
