# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: r

before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y libmagick++-dev

apt_packages:
    - libgsl0-dev
    - libgsl0ldbl
    - libxml2-dev

r_build_args: --no-build-vignettes --no-manual
r_check_args: --no-build-vignettes --no-manual

r_binary_packages:
    - Rcpp
    - RcppGSL
    - roxygen2
    - tidyverse
    - devtools
    - stringi
    - covr
    - qpdf

warnings_are_errors : false

after_success:
  - Rscript -e 'library(covr); codecov()'
