# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: r

apt_packages:
    - libgsl0-dev
    - libgsl0ldbl
    
r_binary_packages:
    - Rcpp
    - RcppGSL
 
r_github_packages: 
    - rmetaverse/pubBias
    - mcguinlu/robvis
    - elizagrames/litsearchr
    - tidymodels/broom
    - malcolmbarrett/tidymeta
    - wviechtb/metadat
    - malcolmbarrett/mbmisc
    - rmetaverse/pubBias

r_build_args: --no-build-vignettes --no-manual
r_check_args: --no-build-vignettes --no-manual

warnings_are_errors : false
